### ISSUE TITLE
Ownership in onConnectionSuccess

### ISSUE THREAD

**Issue by yhvh** [nuttawutmalee/react-native-bluetooth-serial-next#3] opened 2018-12-10 23:59 UTC
**Describe the bug**
In onConnectionSuccess both sendEvent and promise.resolve get a copy of device causing an error.

**To Reproduce**
connect to device observe:
`D BluetoothSerial: Connected
D BluetoothSerial: Connected to device id 88:6B:0F:91:2F:77
D BluetoothSerial: Create ConnectedThread
I BluetoothSerial: Begin mConnectedThread
D BluetoothSerial: device88:6B:0F:91:2F:77
D BluetoothSerial: Sending event: connectionSuccess
E AndroidRuntime: FATAL EXCEPTION: ConnectThread
E AndroidRuntime: Process: com.example, PID: 6827
E AndroidRuntime: com.facebook.react.bridge.ObjectAlreadyConsumedException: Map already consumed
E AndroidRuntime:        at com.facebook.react.bridge.WritableNativeArray.pushNativeMap(Native Method)
E AndroidRuntime:        at com.facebook.react.bridge.WritableNativeArray.pushMap(WritableNativeArray.java:53)
E AndroidRuntime:        at com.facebook.react.bridge.Arguments.fromJavaArgs(Arguments.java:187)
E AndroidRuntime:        at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:32)
E AndroidRuntime:        at com.facebook.react.bridge.PromiseImpl.resolve(PromiseImpl.java:30)
E AndroidRuntime:        at com.nuttawutmalee.RCTBluetoothSerial.RCTBluetoothSerialModule.onConnectionSuccess(RCTBluetoothSerialModule.java:601)
E AndroidRuntime:        at com.nuttawutmalee.RCTBluetoothSerial.RCTBluetoothSerialService.connectionSuccess(RCTBluetoothSerialService.java:224)
E AndroidRuntime:        at com.nuttawutmalee.RCTBluetoothSerial.RCTBluetoothSerialService.access$500(RCTBluetoothSerialService.java:28)
E AndroidRuntime:        at com.nuttawutmalee.RCTBluetoothSerial.RCTBluetoothSerialService$ConnectThread.run(RCTBluetoothSerialService.java:369)
`

**Expected behavior**
Expected connection

**Comment by nuttawutmalee** [comment] 2018-12-11 08:17
#4

**Comment by nuttawutmalee** [comment] 2018-12-28 21:35
Duplicate of #5

**Closed** 2018-12-28 21:35 UTC
Labels: bug
